# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "template-app-ts"
client_id = "f9c63bc752b6261c333730e08996fe36"
application_url = "https://florists-activated-extend-caused.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://florists-activated-extend-caused.trycloudflare.com/auth/callback",
  "https://florists-activated-extend-caused.trycloudflare.com/auth/shopify/callback",
  "https://florists-activated-extend-caused.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "muirwood-apps.myshopify.com"
